use_frameworks!

platform :ios, '8.0'

target 'YYChatMarqueeLabelView_Example' do
  pod 'YYChatMarqueeLabelView', :path => '../'

  target 'YYChatMarqueeLabelView_Tests' do
    inherit! :search_paths

    
  end
end
